### ISSUE TITLE
Combining mask with letters and numeric keyboard

### ISSUE THREAD

**Issue by dmitrikudrenko** [TinkoffCreditSystems/decoro#11]
I defined mask for Webmoney wallet
```
public static final Slot[] WEBMONEY_WALLET = {
            PredefinedSlots.hardcodedSlot('R').withTags(Slot.TAG_DECORATION),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit(),
            PredefinedSlots.digit()
    };
```
and set ```android:inputType="number"``` on EditText. In result, user don't see 'R' sign, it replaced by '9'

**Comment by meandnano** [comment]
It's not actually getting replaced. Android simply won't allow to display letters in a "phone" EditText.

You may try using "phone" input type which allows numbers, spaces and some letters. But I'm not sure about 'R' though.

**Comment by dmitrikudrenko** [comment]
I solved the problem by setting ```android:inputType="text"``` to ```EditText``` in layout and usage ```editText.setRawInputType(InputType.TYPE_CLASS_NUMBER);``` in code. It allows use letters in EditText and shows numeric keyboard to user.
p.s.: it is not a problem of your library, but it is point for improvement

**Comment by neviscom** [comment]
Same thing. It's not obvious that I can't use inputType=number for masks with " " or "-", for example, PredefinedSlots.RUS_PASSPORT.
Maybe you should add some information about it in Readme.
