### ISSUE TITLE
Implementing releases

### ISSUE THREAD

**Issue by Nublo** [TinkoffCreditSystems/decoro#16]
Hi, guys.
First thanks for pretty nice library that you created.
It is really simply for using and have nice functionality.
Also you are still working on it, updating and fixing bugs. That's cool!

But i found that you don't write anywhere changes and updates on new versions.
You can write down it inside releases track, like retrofit doing. Or maybe just create Updates.md file with list of changes in new version.
https://github.com/square/retrofit/releases

So what are you think about it?

**Comment by Vittt2008** [comment]
Hi @Nublo @VertaZoom @busylee999
We want to create the new version of library decoro-2.0.
After release we will make changelog with all changes
