### ISSUE TITLE
android:inputType="phone"

### ISSUE THREAD

**Issue by sashamerkulev** [TinkoffCreditSystems/decoro#21]
Эта штука работает
        Slot[] codeSlots = new UnderscoreDigitSlotsParser().parseSlots("___-___");
        codeMask = MaskImpl.createTerminated(codeSlots); 
        codeMask.setShowingEmptySlots(true);
        codeWatcher = new MaskFormatWatcher(codeMask);
        codeWatcher.installOn(registerCode); 

только если у EditText registorCode, выставлено android:inputType="phone"
если поставить android:inputType="number" то не работает.

можете, что-нибудь подсказать?

**Comment by Vittt2008** [comment]
Этот вопрос уже поднимался в Issue https://github.com/TinkoffCreditSystems/decoro/issues/5

> Если вы используете Decoro для форматирования текста в EditText имейте ввиду следующее. Если от пользователя требуется вести только цифры (номер телефона, карты, дату и т.д.), то inputType для вашего EditText НЕ должен быть InputType.TYPE_CLASS_NUMBER. В поле с TYPE_CLASS_NUMBER андроид не позволит вписать не-цифры и это сломает весь форматтинг. Поэтому используйте InputType.TYPE_CLASS_PHONE для таких случаев.

Поэтому просто используйте InputType.TYPE_CLASS_PHONE
