### ISSUE TITLE
При вводе номера телефона если ввести 7, то показывается просто маска.

### ISSUE THREAD

**Issue by Bakyt-Itigulov** [TinkoffCreditSystems/decoro#35]
Всем привет!

В текстовом поле пользователь вводит свой номер телефона. Если ввести любую цифру (например 9), то в поле сразу показывается:
+7 (9

Но если в качестве первой цифры ввести 7, то просто показывается сама маска:
+7 (

Мне нужно чтобы при вводе цифры 7 выходила такая последовательность:
+7 (7

Что можно сделать чтобы добиться этого?

**Comment by al-dr** [comment]
В описанной ситуации для второй позиции (там где 7) включены обе опции  Slot.RULE_INPUT_MOVES_INPUT | Slot.RULE_INPUT_REPLACE; 
Это позволяет вставить в данный слот только 7, а все остальные значения в данной позиции размещать нельзя.
Если оставить в качестве правил вставки для второй позиции только Slot.RULE_INPUT_MOVES_INPUT, то все значения которые могли бы попасть в это место из предыдущих позиций пройдут дальше. Это должно привести к желаемому поведению.

**Comment by Bakyt-Itigulov** [comment]
Получилось. Спасибо большое.
