### ISSUE TITLE
Работа со вставками текста

### ISSUE THREAD

**Issue by OlegZhilo** [TinkoffCreditSystems/decoro#36]
Подскажите пожалуйста, как лучше сконфигурировать слоты или редактировать текст перед вставкой, чтобы можно было вставлять текст в поле. 
Например маска (___) ___-__-__, а вставить я хочу телефона +7 918 1231245
В такую маску вставить только если телефон будет вида 8 918 123124 и то получается, что он будет вставляться с самого начала и последняя цифра пропадет.

**Comment by al-dr** [comment]
Добрый день, из описания не совсем понятно какое именно требуется поведение от маски. Но попробовать можно перед вставкой убрать все не цифры из номера.

**Comment by al-dr** [comment]
В demo на экране "слоты" если в первое поле вставить номер в указанном Вами формате +7 918 123-12-45  то в поле будет +7 (918) 123-12-45

**Comment by OlegZhilo** [comment]
@al-dr благодарю за ответ. К сожалению проблема оказалась немного глубже, т.к маски динамические и просто захардкожеными правилами тут не обойтись. Но в какую сторону копать - понятно.
