### ISSUE TITLE
+7 (7.......

### ISSUE THREAD

**Issue by eduard1abdulmanov123** [TinkoffCreditSystems/decoro#55]
Добрый день. Подскажите, пожалуйста, как можно решить следующую задачу.  При использовании маски RUS_NUMBER_PHONE происходит следующее. Если я вставляю первым символом семерку, я получаю + 7 (7, а + 7 (, то есть семерка просто съедается, а курсор перемещается за скобку. Если ввести любой другой символ, то он напишется за скобкой. Как можно сделать аналогичное поведение и для 7. То есть при вводе первой семерки, ставить 7 за скобкой, а не прогладывать ее.

**Comment by al-dr** [comment]
можно для 7 (2 слот) попробовать указать правило вставки  Slot.RULE_INPUT_MOVES_INPUT

` slots[1].setFlags(Slot.RULE_INPUT_MOVES_INPUT);`

**Comment by eduard1abdulmanov123** [comment]
Да, спасибо большое, это сработало. То есть получается, что RULE_INPUT_REPLACE в связке с RULE_INPUT_MOVES_INPUT заменяет текущей hardcode, если символы совпадают, а остальные проталкиваются. А если указать только RULE_INPUT_REPLACE, то все символы будут проталкиваться дальше.

**Comment by al-dr** [comment]
да. 

так же добавлю что изначальное поведение с 7 мы считаем комфортным для пользователя при вводе российских номеров. исходим из предположения, что если в изначально пустое поле человек ввел 7, то скорее всего "имел ввиду" он все же 7 - которая код страны.

**Comment by eduard1abdulmanov123** [comment]
Понял Вас. Спасибо большое!
