### ISSUE TITLE
MaskFormatWatcher argument constructor

### ISSUE THREAD

**Issue by MrVilkaman** [TinkoffCreditSystems/decoro#6]
Now it used MaskImpl for constructor argument. Why not Mask?

**Comment by meandnano** [comment]
Because MaskFormatWatcher users copy constructor of MaskImpl.

**Comment by MrVilkaman** [comment]
@meandnano Your example (from habrahabr\readme) is wrong
```
Mask mask = MaskImpl.createTerminated(PredefinedSlots.CARD_NUMBER_USUAL);
FormatWatcher watcher = new MaskFormatWatcher(mask);
watcher.installOn(editText); // install on any TextView
```
mask not instanceof MaskImpl ( second line )

Why do not you use an abstraction l for MaskFormatWatcher  constructor argument? Depend on the specific implementation of mistaken.

maybe need rename  MaskFormatWatcher ->  MaskImplFormatWatcher ?

**Comment by meandnano** [comment]
We've corrected our example. Thanks for this notice.
But MaskFormatWatcher will stay the same yet.
