### ISSUE TITLE
Mispellings in PredefinedSlots.java

### ISSUE THREAD

**Issue by RustamG** [TinkoffCreditSystems/decoro#7]
Hi guys!

There are some constants in PredefinedSlots.java which have typos:

`CARD_NUMBER_STANDART`,
`CARD_NUMBER_STANDART_MASKABLE`.

I guess it should be CARD_NUMBER_STANDAR**D**, CARD_NUMBER_STANDAR**D**_MASKABLE (letter 'D' instead of 'T')

Thank you.

**Comment by meandnano** [comment]
Hi Rustam,

Yeah these are mistakes. Will be fixed in a next release (1.2.0).

Thank you!

**Comment by meandnano** [comment]
1.2.0 Released. Spelling fixed.
